import React from 'react';
import { X, Printer, ShieldCheck, FileText } from 'lucide-react';
import { BatchPassport } from '../../types/spectraguard';

interface AuditReportModalProps {
  passport: BatchPassport;
  onClose: () => void;
}

export const AuditReportModal: React.FC<AuditReportModalProps> = ({ passport, onClose }) => {
  return (
    <div className="fixed inset-0 bg-slate-950/80 backdrop-blur-md z-50 flex items-center justify-center p-4">
      <div className="bg-slate-900 border border-slate-800 rounded-2xl max-w-2xl w-full p-6 shadow-2xl space-y-5 max-h-[90vh] overflow-y-auto">
        <div className="flex items-center justify-between border-b border-slate-800 pb-4">
          <div className="flex items-center space-x-3">
            <div className="p-2 bg-indigo-500/10 border border-indigo-500/30 rounded-xl text-indigo-400">
              <FileText className="w-6 h-6" />
            </div>
            <div>
              <h3 className="font-bold font-mono text-slate-100 text-base">
                Batch Compliance & Quality Inspection Audit Report
              </h3>
              <p className="text-xs text-slate-400">Generated by SpectraGuard X Safety Engine v2.5</p>
            </div>
          </div>
          <button onClick={onClose} className="p-1 hover:bg-slate-800 rounded text-slate-400">
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Report Content */}
        <div className="bg-slate-950 p-5 rounded-xl border border-slate-800 space-y-4 font-mono text-xs text-slate-300">
          <div className="grid grid-cols-2 gap-4 pb-3 border-b border-slate-800 text-[11px]">
            <div>
              <span className="text-slate-500">BATCH IDENTIFIER:</span>
              <div className="font-bold text-cyan-400">{passport.batchId}</div>
            </div>
            <div>
              <span className="text-slate-500">FOOD PROFILE:</span>
              <div className="font-bold text-purple-300">{passport.productName}</div>
            </div>
            <div>
              <span className="text-slate-500">AI MODEL VERSION:</span>
              <div className="font-bold text-slate-200">{passport.modelVersion}</div>
            </div>
            <div>
              <span className="text-slate-500">INSPECTION TIMELINE:</span>
              <div className="font-bold text-slate-200">{passport.startedAt}</div>
            </div>
          </div>

          {/* Audit Metrics Table */}
          <div className="space-y-2">
            <div className="flex justify-between py-1 border-b border-slate-800/80">
              <span className="text-slate-400">Total Products Inspected:</span>
              <span className="font-bold text-slate-100">{passport.totalInspected.toLocaleString()}</span>
            </div>
            <div className="flex justify-between py-1 border-b border-slate-800/80">
              <span className="text-slate-400">Verified Normal (Passed):</span>
              <span className="font-bold text-emerald-400">{passport.normalCount.toLocaleString()} ({((passport.normalCount/Math.max(1, passport.totalInspected))*100).toFixed(1)}%)</span>
            </div>
            <div className="flex justify-between py-1 border-b border-slate-800/80">
              <span className="text-slate-400">Known Defects Isolated:</span>
              <span className="font-bold text-rose-400">{passport.knownAnomalyCount}</span>
            </div>
            <div className="flex justify-between py-1 border-b border-slate-800/80">
              <span className="text-slate-400">Unknown Anomaly (Lab Dispatched):</span>
              <span className="font-bold text-purple-400">{passport.unknownAnomalyCount}</span>
            </div>
            <div className="flex justify-between py-1 border-b border-slate-800/80">
              <span className="text-slate-400">Inspection Coverage Guarantee:</span>
              <span className="font-bold text-cyan-400">{passport.coverageGuaranteePct}% (100% Target)</span>
            </div>
            <div className="flex justify-between py-1">
              <span className="text-slate-400">Average Sensor Subsystem Health:</span>
              <span className="font-bold text-emerald-400">{passport.overallSensorHealthPct}%</span>
            </div>
          </div>

          <div className="p-3 bg-indigo-950/40 border border-indigo-500/30 rounded-lg text-[10px] text-indigo-300">
            ✓ AUDIT PASSED: This production batch satisfies all USDA/FSSAI multi-modal spectral safety standards.
          </div>
        </div>

        <div className="flex justify-end space-x-2">
          <button
            onClick={() => window.print()}
            className="px-4 py-2 bg-indigo-600 hover:bg-indigo-500 text-white font-bold font-mono text-xs rounded-xl shadow-lg transition-all flex items-center gap-2"
          >
            <Printer className="w-4 h-4" /> Print / Save PDF
          </button>
        </div>
      </div>
    </div>
  );
};
